
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 8;
  public static final int LT = 10;
  public static final int OVER = 9;
  public static final int ELSE = 2;
  public static final int PLUS = 6;
  public static final int INT = 27;
  public static final int RBRACE = 24;
  public static final int RPAREN = 20;
  public static final int LTE = 11;
  public static final int SEMI = 17;
  public static final int WHILE = 5;
  public static final int RETURN = 4;
  public static final int EQE = 15;
  public static final int ERROR = 29;
  public static final int IF = 3;
  public static final int LBRACE = 23;
  public static final int LPAREN = 19;
  public static final int GT = 12;
  public static final int ID = 25;
  public static final int GTE = 13;
  public static final int NUM = 26;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int LSQUARE = 21;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int EQ = 14;
  public static final int RSQUARE = 22;
  public static final int VOID = 28;
  public static final int NEQ = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ELSE",
  "IF",
  "RETURN",
  "WHILE",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "EQ",
  "EQE",
  "NEQ",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LSQUARE",
  "RSQUARE",
  "LBRACE",
  "RBRACE",
  "ID",
  "NUM",
  "INT",
  "VOID",
  "ERROR"
  };
}

